### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by colinlet** [Moeditor/Moeditor#61]
Uncaught Exception:
Error: EACCES: permission denied, open '/Users/***/.config/configstore/Moeditor.json'
You don't have access to this file.

at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:167:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:500:29)
    at Object.get (/Applications/Moeditor.app/Contents/Resources/app.asar/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/Applications/Moeditor.app/Contents/Resources/app.asar/node_modules/configstore/index.js:28:44)
    at MoeditorApplication.run (/Applications/Moeditor.app/Contents/Resources/app.asar/app/moe-app.js:53:23)
    at App.app.on (/Applications/Moeditor.app/Contents/Resources/app.asar/app/index.js:34:9)
    at emitOne (events.js:101:20)

**Comment by Menci** [comment]
Moeditor need to read/write `~/.config/configstore/Moeditor.json` for config.

Try checking the permission of the file and directory, make sure yourself can read/write that file.
